apiVersion: v1
kind: Pod
metadata:
  name: mongo-test
spec:
  containers:
  - name: mongo
    image: bitnami/mongodb:latest
    ports:
    - containerPort: 27017
    volumeMounts:
    - mountPath: /data/db
      name: mongo-storage
  volumes:
  - name: mongo-storage
    persistentVolumeClaim:
      claimName: test-claim
