replicaCount: 2

image:
  repository: 851725552187.dkr.ecr.us-east-1.amazonaws.com/app-repository
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

mongodb:
  url: "mongodb://dbadmin:Aa123456!@my-mongodb.default.svc.cluster.local:27017/db"