apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "851725552187.dkr.ecr.us-east-1.amazonaws.com/app-repository:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_URL
              value: mongodb://dbadmin:Aa123456!@app-db-cluster.cluster-c5a8oseiy1q2.us-east-1.docdb.amazonaws.com:27017/db
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
